version: '3'
services:
  app:
    build: ./docker/php
    container_name: skillup_app
    volumes:
      - ./www:/var/www
    depends_on:
      - database
  app2:
    build: ./docker/php
    container_name: skillup_app
    volumes:
      - ./www:/var/www
    depends_on:
      - database
  nginx:
    image: nginx:1.17
    container_name: skillup_nginx
    ports:
      - 8011:80
    volumes:
      - ./www:/var/www
      - ./docker/nginx/skillup.local.conf:/etc/nginx/conf.d/skillup.local.conf
    depends_on:
      - app
  database:
    image: mysql
    ports:
      - 3306:3306
    container_name: mysql-mainacad
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ALLOW_EMPTY_PASSWORD: 1